[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.4.1",
    "google-genai>=1.62.0",
    "onnxruntime<1.20.0",
    "python-dotenv>=1.2.1",
    "sentence-transformers>=5.2.2",
]
